version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fortnite
      POSTGRES_USER: fortnite
      POSTGRES_PASSWORD: fortnite
    ports: ['5432:5432']
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
